/**
 * The testing dashboard (TESTING.md §6).
 *
 * One self-contained HTML file with the run's data inlined — it opens from
 * file://, needs no server and no network, which is the same constitution the
 * app itself is built under (ADR-002). Generated by scripts/report.mjs at the
 * end of every run.
 *
 * The sections are ordered by what gets asked first: did it pass, what is
 * covered, what broke, what is flaky, what is getting slower.
 */

const esc = (s) =>
  String(s).replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c],
  );

const CELL_CLASS = {
  passed: 'ok',
  failed: 'bad',
  missing: 'missing',
  planned: 'planned',
  exempt: 'exempt',
  'n/a': 'na',
};

const CELL_TEXT = {
  passed: 'pass',
  failed: 'FAIL',
  missing: 'missing',
  planned: 'planned',
  exempt: 'exempt',
  'n/a': '·',
};

/**
 * A test whose outcome has varied across runs at the same commit is flaky by
 * definition — the code did not change, so the test did. That is the only
 * signal worth acting on, and it needs history rather than one run.
 */
function flakiness(history) {
  const seen = new Map();
  for (const run of history) {
    const failed = new Set((run.failed ?? []).map((f) => f.name));
    for (const name of failed) {
      const e = seen.get(name) ?? { name, fails: 0, runs: 0, commits: new Set() };
      e.fails += 1;
      e.commits.add(run.commit);
      seen.set(name, e);
    }
  }
  // Count total appearances so a test that always fails is not called flaky.
  for (const run of history) {
    for (const e of seen.values()) e.runs += 1;
    void run;
  }
  return [...seen.values()]
    .map((e) => ({ ...e, commits: e.commits.size, rate: e.fails / Math.max(e.runs, 1) }))
    .filter((e) => e.rate < 1)
    .sort((a, b) => b.fails - a.fails)
    .slice(0, 15);
}

function sparkline(values, width = 220, height = 34) {
  if (values.length === 0) return '';
  const max = Math.max(...values, 1);
  const step = width / Math.max(values.length - 1, 1);
  const pts = values
    .map((v, i) => `${(i * step).toFixed(1)},${(height - 2 - (v / max) * (height - 6)).toFixed(1)}`)
    .join(' ');
  return `<svg viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" aria-hidden="true"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg>`;
}

export function renderDashboard({ summary, matrix, tests, history, layers, coverage }) {
  const rows = [...matrix.values()];
  const allLayers = Object.keys(rows[0]?.cells ?? {});
  const failures = tests.filter((t) => t.status === 'failed');
  const flaky = flakiness(history);
  const durations = history.slice(-30).map((h) => Math.round((h.totals?.tests ?? 0) || 0));
  const passRates = history
    .slice(-30)
    .map((h) => Math.round(((h.totals?.passed ?? 0) / Math.max(h.totals?.tests ?? 1, 1)) * 100));

  const slowest = [...tests].sort((a, b) => b.duration - a.duration).slice(0, 20);

  const matrixRows = rows
    .map(
      (r) => `<tr>
        <th scope="row"><a href="features/${esc(r.feature.id)}.md">${esc(r.feature.id)}</a>
          <span class="dim">${esc(r.feature.area)}</span></th>
        ${allLayers
          .map((l) => `<td class="${CELL_CLASS[r.cells[l]]}">${CELL_TEXT[r.cells[l]]}</td>`)
          .join('')}
      </tr>`,
    )
    .join('\n');

  return `<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RepoCircle — test dashboard</title>
<style>
  :root {
    --bg: #0E0F12; --panel: #15171C; --line: #23262E;
    --text: #E7E9EE; --dim: #9AA1AD; --faint: #6B7280;
    --ok: #4ADE80; --bad: #F87171; --warn: #FBBF24; --accent: #7DA2FF;
    --mono: ui-monospace, SFMono-Regular, Menlo, monospace;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--text);
    font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif; }
  main { max-width: 1180px; margin: 0 auto; padding: 32px 20px 80px; }
  h1 { font-size: 20px; font-weight: 600; margin: 0 0 4px; letter-spacing: -0.01em; }
  h2 { font-size: 15px; font-weight: 600; margin: 36px 0 12px; letter-spacing: -0.01em; }
  .dim { color: var(--dim); } .faint { color: var(--faint); }
  .sub { color: var(--dim); margin: 0 0 24px; font-size: 13px; }
  .verdict { display: flex; gap: 10px; flex-wrap: wrap; margin: 20px 0 8px; }
  .tile { background: var(--panel); border: 1px solid var(--line); border-radius: 10px;
    padding: 12px 14px; min-width: 128px; }
  .tile .k { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--faint); }
  .tile .v { font-size: 20px; font-weight: 600; margin-top: 3px; }
  .v.ok { color: var(--ok); } .v.bad { color: var(--bad); }
  table { border-collapse: collapse; width: 100%; font-size: 13px; }
  th, td { border-bottom: 1px solid var(--line); padding: 7px 9px; text-align: left; }
  thead th { color: var(--faint); font-weight: 500; font-size: 11px;
    text-transform: uppercase; letter-spacing: 0.05em; }
  tbody th { font-weight: 500; }
  td.ok { color: var(--ok); } td.bad { color: var(--bad); font-weight: 600; }
  td.missing { color: var(--warn); } td.planned { color: var(--dim); }
  td.exempt, td.na { color: var(--faint); }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  a:focus-visible, [tabindex]:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
  .scroll { overflow-x: auto; border: 1px solid var(--line); border-radius: 10px; background: var(--panel); }
  .scroll table { min-width: 720px; }
  pre { background: #0B0C0F; border: 1px solid var(--line); border-radius: 8px;
    padding: 10px 12px; overflow-x: auto; font: 12px/1.5 var(--mono); color: var(--dim); }
  code { font-family: var(--mono); font-size: 12px; }
  .empty { color: var(--faint); padding: 14px 2px; }
  .trend { display: flex; gap: 28px; flex-wrap: wrap; align-items: flex-end; color: var(--accent); }
  .trend figure { margin: 0; }
  .trend figcaption { color: var(--faint); font-size: 11px; text-transform: uppercase;
    letter-spacing: 0.05em; margin-bottom: 4px; }
  @media (prefers-color-scheme: light) {
    :root:not([data-theme="dark"]) { --bg:#FBFBFD; --panel:#fff; --line:#E5E7EB;
      --text:#111827; --dim:#4B5563; --faint:#6B7280; }
  }
</style>
</head>
<body>
<main>
  <h1>RepoCircle — test dashboard</h1>
  <p class="sub">
    Run <code>${esc(summary.runId)}</code> ·
    <code>${esc(summary.env.commit.slice(0, 7))}</code> on <code>${esc(summary.env.branchName)}</code>
    ${summary.env.dirty ? '· <span class="faint">working tree dirty</span>' : ''}
  </p>

  <div class="verdict">
    <div class="tile"><div class="k">Verdict</div>
      <div class="v ${summary.totals.failed === 0 ? 'ok' : 'bad'}">
        ${summary.totals.failed === 0 ? 'pass' : `${summary.totals.failed} failed`}</div></div>
    <div class="tile"><div class="k">Tests</div><div class="v">${summary.totals.passed}/${summary.totals.tests}</div></div>
    <div class="tile"><div class="k">Wall time</div><div class="v">${(summary.durationMs / 1000).toFixed(0)}s</div></div>
    <div class="tile"><div class="k">Matrix passing</div><div class="v">${summary.matrix.passed}</div></div>
    <div class="tile"><div class="k">Still to build</div><div class="v">${summary.matrix.planned + summary.matrix.missing}</div></div>
  </div>

  <h2>Layers</h2>
  <div class="scroll"><table>
    <thead><tr><th>Layer</th><th>Tests</th><th>Passed</th><th>Failed</th></tr></thead>
    <tbody>${Object.entries(layers)
      .map(
        ([name, l]) =>
          `<tr><th scope="row">${esc(name)}</th><td>${l.tests}</td><td class="ok">${l.passed}</td><td class="${l.failed ? 'bad' : ''}">${l.failed}</td></tr>`,
      )
      .join('')}</tbody>
  </table></div>

  <h2>Feature matrix</h2>
  <p class="sub">Every feature in the registry against every layer. <span class="dim">missing</span> is
     declared but unbuilt and unplanned; <span class="dim">planned</span> is in KNOWN_GAPS with an owning milestone.</p>
  <div class="scroll"><table>
    <thead><tr><th>Feature</th>${allLayers.map((l) => `<th>${esc(l)}</th>`).join('')}</tr></thead>
    <tbody>${matrixRows}</tbody>
  </table></div>

  <h2>Failures</h2>
  ${
    failures.length === 0
      ? '<p class="empty">None in this run.</p>'
      : failures
          .map(
            (f) => `<div><strong>${esc(f.name)}</strong>
              <p class="sub"><code>${esc(f.filePath)}</code> · ${esc(f.extra.layer)}
              ${f.tags.length ? '· ' + f.tags.map((t) => `<code>${esc(t)}</code>`).join(' ') : ''}</p>
              <pre>${esc((f.message ?? '').slice(0, 2500))}</pre></div>`,
          )
          .join('')
  }

  <h2>Flakiness</h2>
  <p class="sub">Tests whose outcome has varied across recorded runs. A test that always fails is a
     bug; one that sometimes fails is a maintenance queue.</p>
  ${
    flaky.length === 0
      ? '<p class="empty">Nothing has flaked across the recorded runs.</p>'
      : `<div class="scroll"><table>
          <thead><tr><th>Test</th><th>Failures</th><th>Distinct commits</th></tr></thead>
          <tbody>${flaky
            .map(
              (f) =>
                `<tr><th scope="row">${esc(f.name)}</th><td>${f.fails}</td><td>${f.commits}</td></tr>`,
            )
            .join('')}</tbody></table></div>`
  }

  <h2>Trends</h2>
  <div class="trend">
    <figure><figcaption>Tests per run (last ${durations.length})</figcaption>${sparkline(durations)}</figure>
    <figure><figcaption>Pass rate %</figcaption>${sparkline(passRates)}</figure>
  </div>

  <h2>Coverage</h2>
  ${
    !coverage
      ? '<p class="empty">Not collected in this run — <code>npm run coverage</code>.</p>'
      : `<p class="sub">Merged from ${esc(coverage.generatedFrom.join(', '))} over ${coverage.files}
         source files. The floor is a ratchet: it may rise, never fall.</p>
        <div class="verdict">
          ${Object.entries(coverage.overall)
            .map(
              ([k, v]) =>
                `<div class="tile"><div class="k">${esc(k)}</div><div class="v">${v}%</div></div>`,
            )
            .join('')}
        </div>
        <div class="scroll" style="margin-top:14px"><table>
          <thead><tr><th>Feature</th><th>Statements</th><th>%</th></tr></thead>
          <tbody>${Object.entries(coverage.features)
            .sort((a, b) => a[1].pct - b[1].pct)
            .map(
              ([fid, c]) =>
                `<tr><th scope="row">${esc(fid)}</th><td class="dim">${c.covered}/${c.total}</td><td class="${c.pct >= 60 ? 'ok' : c.pct >= 20 ? '' : 'missing'}">${c.pct}%</td></tr>`,
            )
            .join('')}</tbody>
        </table></div>`
  }

  <h2>Slowest tests</h2>
  <div class="scroll"><table>
    <thead><tr><th>Test</th><th>Layer</th><th>ms</th></tr></thead>
    <tbody>${slowest
      .map(
        (t) =>
          `<tr><th scope="row">${esc(t.name.slice(0, 110))}</th><td class="dim">${esc(t.extra.layer)}</td><td>${t.duration}</td></tr>`,
      )
      .join('')}</tbody>
  </table></div>

  <p class="sub" style="margin-top:40px">
    Generated by <code>npm run report</code>. Machine-readable: <a href="ctrf.json">ctrf.json</a> ·
    <a href="summary.json">summary.json</a> · <a href="../../INDEX.md">index</a>
  </p>
</main>
</body>
</html>`;
}
